# Generated by Django 2.2.7 on 2020-02-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activateboolean',
            old_name='activate_email_company',
            new_name='activate',
        ),
        migrations.RemoveField(
            model_name='activateboolean',
            name='activate_email_user',
        ),
        migrations.AddField(
            model_name='activateboolean',
            name='activation_type',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtype',
            name='email_type',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
